//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WMLFsp.rc
//
#define IDS_OK                          3
#define IDS_CANCEL                      4
#define IDS_LOGIN                       5
#define IDS_MSG_SEND                    6
#define IDS_MSG_CLOSE                   7
#define IDS_MSG_CHANGE                  8
#define IDS_SHOW_MENU                   9
#define IDS_FB_ADD                      10
#define IDS_OPTION                      11
#define IDS_LOGIN_REMPASS               12
#define IDS_LGOIN_AUTODIAL              13
#define IDS_EXIT                        14
#define IDS_MAIN_ADDBUDDY               15
#define IDS_MAIN_STATE                  16
#define IDS_MAIN_STATE_ONLINE           17
#define IDS_MAIN_STATE_HIDE             18
#define IDS_MAIN_STATE_BUSY             19
#define IDS_MAIN_SHOWNEWMSG             20
#define IDD_WMLF_DIALOG                 102
#define IDD_WMLF_MAIN                   104
#define IDR_MAINFRAME                   128
#define IDR_MENU_BUDDY                  131
#define IDB_BITMAP_AWAY                 133
#define IDB_BITMAP_BLACK                134
#define IDB_BITMAP_BUSY                 135
#define IDB_BITMAP_DINNER               136
#define IDB_BITMAP_EXAWAY               137
#define IDR_MSG_MENU                    137
#define IDB_BITMAP_MEET                 138
#define IDB_BITMAP_MOBILE               139
#define IDS_MAIN_STATE_AWAY             139
#define IDB_BITMAP_NUMP                 140
#define IDS_MAIN_SET_SILENCE            140
#define IDB_BITMAP_OFFLINE              141
#define IDS_MAIN_SET_VIBR               141
#define IDB_BITMAP_ONLINE               142
#define IDS_MAIN_MINIMAL                142
#define IDB_BITMAP_PHONE                143
#define IDS_MAIN_LOGOFF                 143
#define IDB_BITMAP_REFUSE               144
#define IDB_BITMAP_WAIT                 145
#define IDR_MSGSOUND                    148
#define IDB_BITMAP_QUN                  149
#define IDB_BITMAP_FLICK                159
#define IDR_MAIN_MENU                   160
#define IDR_LOGIN_MENU                  161
#define IDB_BITMAP1                     162
#define IDB_BITMAP_BIGLOGO              162
#define IDB_BITMAP_USERHEAD             164
#define IDD_WMLF_FINDBUDDY              165
#define IDR_MENU_FINDBUDDY              166
#define IDD_WMLF_BUDDYINFO              167
#define IDR_MENU_BUDDYINFO              169
#define IDB_BITMAP2                     170
#define IDB_BITMAP_FIND                 170
#define IDD_WMLF_ABOUT                  171
#define IDR_MENU_ABOUT                  172
#define IDD_WMLF_MSG_VIEW               172
#define IDR_MSG_POP_MENU                174
#define IDR_ONLINESOUND                 175
#define IDB_BITMAP_ONLINE_M             177
#define IDB_BITMAP_AWAY_M               178
#define IDB_BITMAP_BUSY_M               179
#define IDD_WMLF_MSG_PAGE               180
#define IDB_BITMAP_NOTREAD              181
#define IDC_BI_CITY                     200
#define IDC_MOBILE_NO                   1000
#define IDC_STATIC_ABOUT                1000
#define IDC_PWD                         1001
#define IDC_LOGIN                       1002
#define IDC_STATIC_PWD                  1003
#define IDC_STATIC_ID                   1004
#define IDC_STATIC_NET                  1005
#define IDC_LOGIN_STATE                 1006
#define IDC_TREE_BUDDY                  1011
#define IDC_MSG_BROWSER                 1013
#define IDC_SEND_MSG                    1019
#define IDC_NET_STATE                   1028
#define IDC_REMPASS                     1033
#define IDC_EDIT_FIND                   1035
#define IDC_BTN_FIND                    1036
#define IDC_BTN_ADD                     1037
#define IDC_HEAD_PIC                    1039
#define IDC_INFO_NAME                   1040
#define IDC_INFO_SIGN                   1041
#define IDC_LOGO                        1042
#define IDC_FB_RD_FXNO                  1043
#define IDC_FB_RD_MOBILE                1044
#define IDC_FB_EDIT_NO                  1045
#define IDC_FB_LIST_INFO                1046
#define IDC_FB_EDIT_NAME                1048
#define IDC_FB_BTN_FIND                 1049
#define IDC_FB_STATIC_NAME              1050
#define IDC_MSG_INFO                    1051
#define IDC_FB_EDIT_NAME2               1051
#define IDC_FB_STATIC_NAME2             1052
#define IDC_BI_LB_NICKNAME              1054
#define IDC_BI_LB_SHOWNAME              1055
#define IDC_BI_EDT_SHOWNAME             1056
#define IDC_BI_GRP_INFO                 1057
#define IDC_BI_LB_NAME                  1058
#define IDC_BI_FETIONNO                 1059
#define IDC_BI_NICKNAME                 1060
#define IDC_BI_NAME                     1061
#define IDC_BI_LB_FETIONNO              1062
#define IDC_BI_LB_SEX                   1063
#define IDC_BI_SEX                      1064
#define IDC_BI_CBO_GROUP                1065
#define IDC_BI_PROV                     1066
#define IDC_BI_LB_PROV                  1067
#define IDC_BI_LB_CITY                  1068
#define IDC_BI_SIGN                     1069
#define IDC_BI_LB_SIGN                  1070
#define IDC_BI_LB_GROUP                 1071
#define IDC_BI_GRP_SET                  1072
#define IDC_FB_STATIC_GROUP             1079
#define IDC_FB_CBO_GROUP                1080
#define IDC_FB_STATIC_INFO              1081
#define IDC_FB_CBO_NUMTYPE              1082
#define IDC_COMBO_USERS                 1083
#define IDC_COMBO_NET                   1084
#define IDC_TAB_CHAT                    1085
#define IDR_MSG_SEND                    32780
#define IDR_MSG_CLOSE                   32783
#define IDR_MSG_CHANGE                  32784
#define ID_RIGHT_TESTE                  32785
#define IDM_MSG_MENU                    32786
#define IDM_MSG_CHANGE                  32787
#define IDM_MSG_CLOSE                   32788
#define IDM_MSG_CHANGE_METHOD           32790
#define ID_LEFT                         32791
#define IDFINDCANCEL                    32802
#define IDM_MAIN_STATE_ONLINE           32802
#define IDM_MAIN_STATE_HIDE             32803
#define IDM_MAIN_STATE_BUSY             32804
#define IDM_MAIN_STATE_AWAY             32805
#define IDM_MAIN_SET_SILENCE            32807
#define IDM_MAIN_SET_VIBR               32808
#define IDM_MAIN_MINIMAL                32809
#define IDM_MAIN_LOGOFF                 32810
#define IDM_LOGIN_LOGIN                 32817
#define IDM_LOGIN_REMPASS               32818
#define IDM_LOGIN_OFFLINE               32819
#define IDM_LOGIN_EXIT                  32820
#define IDM_CANCEL                      32821
#define IDM_LOGIN                       32822
#define IDM_FB_ADD                      32824
#define IDM_MAIN_ADDBUDDY               32827
#define IDM_MAIN_SENDMSG                32828
#define IDM_BD_VIEWINFO                 32829
#define IDM_BD_SENDMSG                  32830
#define IDM_BD_DELETE                   32835
#define IDM_BD_ADDBLACKLIST             32836
#define IDM_BD_MOVEGROUP                32838
#define IDM_MSG_VIEWINFO                32845
#define IDM_FB_SET_MOBILE               32848
#define IDM_FB_SET_FXNO                 32849
#define IDM_ABOUT                       32851
#define IDM_BD_REMOVEBLACK              32853
#define IDM_BD_RMBLACKLIST              32854
#define IDM_MAIN_NOSOUND                32856
#define IDM_MAIN_SET_NOSOUND            32857
#define IDM_MAIN_SHOWNEWMSG             32860
#define IDM_MAIN_DIMISS                 32861
#define IDM_MAIN_SHOWNEWMSG2            32862
#define IDM_COPY1                       32863
#define IDM_COPY2                       32864
#define IDM_PASTE                       32865
#define IDC_BI_LB_MOBILENO              32866
#define IDC_BI_MOBILENO                 32867
#define IDR_LOGIN_CANCEL_MENU           32868
#define IDM_LOGIN_CANCEL                32869
#define IDC_LOGIN_OFFLINE               32870
#define IDM_MAIN_SET_ONLINE             32872
#define IDM_MAIN_CLEAN                  32874
#define IDM_MAIN_SET_SHIELDQUN          32876
#define IDM_MAIN_SET_SHIELDQUNMESSAGE   32877
#define IDM_END_TALK                    32880
#define IDM_NEXT_TALK                   32881
#define IDM_SEND_MYSELF                 32882

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32883
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
